display:
  default:
    display_title: Chính
    display_options:
      exposed_form:
        options:
          submit_button: 'Áp dụng'
          reset_button_label: 'Thiết lập lại'
          exposed_sorts_label: 'Sắp xếp theo'
          sort_asc_label: 'Tăng dần'
          sort_desc_label: 'Giảm dần'
      pager:
        options:
          expose:
            items_per_page_label: 'Số mục trên một trang'
            items_per_page_options_all_label: '- Tất cả -'
            offset_label: 'Độ dịch'
          tags:
            previous: '‹ trước'
            next: 'sau ›'
            first: '« đầu'
            last: 'cuối »'
      fields:
        sensor_status:
          label: 'Trạng thái'
      arguments:
        sensor_name:
          exception:
            title: 'Tất cả'
  detail_page_log:
    display_options:
      fields:
        sensor_status:
          label: 'Trạng thái'
  page_1:
    display_title: Trang
