_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  admin_toolbar: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_content: 0
  blog: 0
  breakpoint: 0
  ckeditor5: 0
  comment: 0
  config: 0
  config_split: 0
  config_translation: 0
  contact: 0
  contextual: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  entity_reference_revisions: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  help: 0
  history: 0
  image: 0
  jquery_ui: 0
  jquery_ui_accordion: 0
  jquery_ui_tabs: 0
  language: 0
  link: 0
  locale: 0
  media: 0
  media_library: 0
  menu_link_content: 0
  menu_ui: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  paragraphs_type_permissions: 0
  path: 0
  path_alias: 0
  quicktabs: 0
  quicktabs_accordion: 0
  quicktabs_jqueryui: 0
  rules: 0
  search: 0
  shortcut: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  toolbar: 0
  tour: 0
  twig_tweak: 0
  typed_data: 0
  update: 0
  user: 0
  views_ui: 0
  content_translation: 10
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  olivero: 0
  claro: 0
  lando_blog: 0
profile: standard
