_core:
  default_config_hash: CXhei_vpaZk-3f_Mj2cH0YmpK-ZpKHoSzVA3yZrDq0g
definitions:
  contact__site_page:
    menu_name: footer
    parent: ''
    weight: 0
    expanded: false
    enabled: true
  user__page:
    weight: -49
    menu_name: account
    parent: ''
    enabled: true
    expanded: false
  user__logout:
    weight: -45
    menu_name: account
    parent: ''
    enabled: true
    expanded: false
