_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: 3f3ee0e4-34e0-437a-ae21-6898e43b0d72
name: 'Drush Site-Install'
mail: admin@example.com
slogan: ''
page:
  403: ''
  404: ''
  front: /homepage
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
