<?php

/**
 * @file
 * Primary module hooks for Blog module.
 */

 function blog_theme() {
    return [
        'blogs' => [
            'template' => 'blogs',
            'variables' => [
              'data' => [],
            ],
          ],
        'carousel' => [
            'template'=> 'carousel',
            'variables' => [
              'data' => [],
            ],
          ],
        'score' => [
            'template'=> 'score',
            'variables' => [
              'data' => [],
            ],
          ],
        'post-details' => [
            'template'=> 'post-details',
            'variables' => [
              'data' => [],
            ],
          ]
        ];       
 }