name: Deploy code to Pantheon
on:
  release:
    types: [published]
  push:
    branches:
      - main
    tags:
      - staging.*
jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Print variable
        run: |
          echo ${{ github.ref_name }}
          echo ${{ github.event.release.name }}
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.PANTHEON_SSH_KEY }}
        config: ${{ secrets.SSH_CONFIG }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: Installing Terminus
      uses: kopepasah/setup-pantheon-terminus@master
      with:
        pantheon-machine-token: ${{ secrets.PANTHEON_MACHINE_TOKEN }}
    - name: Deploy to Pantheon
      env:
        pantheon_repo: '${{ secrets.PANTHEON_REPO }}'
        pantheon_site_name: '${{ secrets.PANTHEON_SITE_NAME }}'
        
      run: | 
        if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
          git remote add pantheon $pantheon_repo
          git push pantheon HEAD:master -f
          commit_message=$(git log -1 --pretty=%B)
        elif [[ ${{ github.ref }} == 'refs/tags/staging'* ]]; then
          git remote add pantheon $pantheon_repo
          git push pantheon HEAD:master -f
          commit_message=$(git log -1 --pretty=%B)
          terminus env:deploy $pantheon_site_name.test --note="Automated deploy: $commit_message"
        elif [[ ${{ github.ref }} == 'refs/tags/release'* ]]; then
          terminus env:deploy $pantheon_site_name.live --note="Automated deploy: $commit_message"
        fi
